[package]
name = "brain-nfts-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.brain-nfts]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.48.0"
default-features = false
